### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by riseshia** [riseshia/hi_friend#1]
- [ ] `include`
- [ ] superclass
- [ ] `extend`
- [ ] class level variable
- [ ] method visibility
- [ ] fixed sized array
- [ ] add flag to clear guess / accurate type
- [ ] save inference log
- [ ] improve inspect
- [x] interpolated string
- [x] skip const read tv creation on class / module declaration
- [x] hash node
- [x] caching inference result
- [x] auto inference after update file
- [x] attr_reader
- [x] attr_writer
- [x] attr_accesssor
- [x] module def from n files
- [x] class def from n files
- [x] file change
- [x] symbol node
- [x] ivar node
- [x] array node
- [x] loc node mapper empty space handling
- [x] Fix union build logic
- [x] inference with context
